---

# UptimeRobot API key MUST BE SET BY THE USER (in config or on the command line).

api_key: nokey # By default, we use a dummy key which won't work!

# Only optional parameters are defaulted here.
# Remember that alerts and monitors are STRINGS, not numbers.

get_monitors:
    monitors: null # e.g ['012', 'my monitor', '1451']
    show_alerts: False
    show_log: False
    log_alerts: False
    log_timezone: False
    uptime: null # e.g [1, 5, 10]

new_monitor:
    type: 1 # http(s)
    subtype: null
    port: null
    keyword_type: null
    keyword: null
    username: null
    password: null
    alerts: null # e.g. ['12315', 'my alert']

edit_monitor:
    # Probably not a good idea to default any of these.
    name: null
    status: null
    url: null
    type: null
    subtype: null
    port: null
    keyword_type: null
    keyword: null
    username: null
    password: null
    alerts: null # e.g. ['12315', 'my alert']

get_alerts:
    alerts: null # e.g. ['12315', 'my alert']

new_alert:
    type: 2 # Default to email



